"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.11.
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Security Settings ---
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'your-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Deployment allow hosts
ALLOWED_HOSTS = ['*']

# Security settings for HTTPS environments (Render/Production)
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- Application Definition ---
INSTALLED_APPS = [
    # Custom Apps (Placed first to allow template overriding)
    'shortener', #

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Site framework required by django-allauth
    'django.contrib.sites', 

    # Authentication backend (django-allauth)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

    # API and documentation tools
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static file handling in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Middleware for django-allauth identity management
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Allow project-level templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# --- Database Configuration ---
# Switches between PostgreSQL (Production) and SQLite (Development)
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600
    )
}

# --- Static and Media Files ---
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Using WhiteNoise for efficient static delivery on Render
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- django-allauth Core Configurations ---

# Required Site ID for allauth (Referencing the record in Admin Site)
SITE_ID = 1 #

# Post-login and post-logout redirection paths
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Redirect signup attempts to login to enforce social-only flow
ACCOUNT_SIGNUP_REDIRECT_URL = '/accounts/login/'

# Streamlined Social Login (One-tap behavior)
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically create account from social data
ACCOUNT_EMAIL_VERIFICATION = 'none' # Skip verification for third-party providers
SOCIALACCOUNT_LOGIN_ON_GET = True # Direct redirection to provider selection
ACCOUNT_LOGOUT_ON_GET = True      # Logout without intermediate confirmation

# Identity and Authentication Rules
ACCOUNT_AUTHENTICATION_METHOD = 'email' # Use email for stable social identity
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

# Social Provider OAuth Settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': ['id', 'email', 'name', 'first_name', 'last_name'],
        'VERSION': 'v17.0',
    }
}

# --- Localization ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Django REST Framework & Documentation (Swagger) ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
} #

SPECTACULAR_SETTINGS = {
    'TITLE': 'URL Shortener API',
    'DESCRIPTION': 'API documentation for URL shortening service with Secure OAuth2 & Basic Auth.',
    'VERSION': '1.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # --- New Security Setting ---
    # Restrict schema and Swagger UI access to admin users (is_staff=True)
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'],
    
    # Authorize button configuration in Swagger UI
    'SECURITY': [
        {
            'basicAuth': [], 
        }
    ],
    
    'COMPONENT_SPLIT_PATCH': True,
    
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': True,
        'persistAuthorization': True,
    },
}

# --- Import local settings if available ---
try:
    from .local import *
except ImportError:
    pass
